# Appendix B

Since the first infected case reported in December 2019, the outbreak of Coronavirus disease (COVID-19) has unfolded across the globe. In the US, coronavirus has infected more than five million people and killed over 160,000 people, as of the time of writing. While essential public health, economic and social science research in measuring and modeling COVID-19 and its effects is underway, reliable and accurate datasets are vital for scientists to conduct related research and for governments to make better decisions [@killeen2020county]. Unfortunately, errors could occur in the data collection process, especially under such a pandemic. In this work, we focus on the data collection, comparison, data inconsistency detection, and the corresponding curating.

Living through unprecedented times, governments must rely on timely, reliable data to make decisions to mitigate harm and support their citizens. Every day, several volunteer groups and organizations work very hard on collecting data on COVID-19 from all the counties and states in the US. There are four primary sources, including (1) the New York Times ([NYT](https://github.com/nytimes/covid-19-data)), (2) the COVID Tracking Project at the Atlantic ([Atlantic](https://covidtracking.com)), (3) the data repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University ([JHU](https://github.com/CSSEGISandData/COVID-19)), and (4) [USAFacts](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map). 

We collect the epidemic data up to county level in the US along with control measures and other local information, such as socioeconomic status, demographic characteristics, healthcare infrastructure, and other essential factors to analyze the spatiotemporal dynamic pattern of the spread of COVID-19. Our data covers about 3,200 county-equivalent areas from 50 US states and the District of Columbia. A live version of the data analysis will be continually updated on the [COVID-19 US Dashboard](https://covid19.stat.iastate.edu) and the [Github Repository](https://github.com/covid19-dashboard-us/cdcar).


## Epidemic Data

The daily counts of cases and deaths of COVID-19 are crucial for understanding how this pandemic is spreading. Thanks to the contribution of the data science communities across the world, multiple sources are providing the COVID-19 data with different precision and focus. In this book, we consider the reported cases from the following four sources: the [NYT](https://github.com/nytimes/covid-19-data), the [Atlantic](https://covidtracking.com), the [JHU](https://github.com/CSSEGISandData/COVID-19), and the [USAFacts](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map). To clean the data, we first fetch data from the above four sources and compile them into the same format for further comparison and cross-validation. 

### State level

In the state level epidemic data, we include the following variables. Among those variables, the variable **State** can be used as the key for data merge.

* **State**: name of state. There are 48 mainland US states and the District of Columbia.

* **XYYYY.MM.DD**: cumulative infection or death cases related to the date of
**YYYY.MM.DD.** **YYYY**, **MM**, and **DD** represent year, month and day, re- spectively. It starts from **X2020.01.22**. For example, the variable **X2020.01.22** is either infection or death cases in a certain state (**State**) on 01/22/2020.


### County level

For county-level data, two more county-specific variables are included. As the key of this table, variable ID can be used for future data merge.

* **ID**: county-level Federal Information Processing System (FIPS) code, which uniquely identifies the geographic area. The number has five digits, of which the first two are the FIPS code of the state to which the county belongs.

* **County**: name of county matched with **ID**. There are about 3,200 counties and county-equivalents (e.g. independent cities, parishes, boroughs) in the US.

* **State**: name of state matched with **ID**. There are 50 states and the District of Columbia in the US.

* **XYYYY.MM.DD**: cumulative infection or death cases related to the date of **YYYY.MM.DD**. **YYYY**, **MM**, and **DD** represent year, month and day, respectively. It starts from **X2020.01.22**. For example, the variable **X2020.01.22** is either infection or death cases in a certain (**County**) on 01/22/2020.


## Other Factors 

When analyzing the reported cases of COVID-19, many other factors may also contribute to the  temporal or spatial patterns; see the discussions in [@wang:2020:comparing]. For example, local features, like socioeconomic and demographic factors, can dramatically influence the course of the epidemic, and thus, the spread of the disease could vary dramatically across different geographical regions. Therefore, these datasets are also supplemented with the population information at the county level in our repository. We further classify these factors into the following six groups.

### Policy Data 

In a race to stunt the spread of COVID-19, federal, state and local governments have issued various executive orders. Government declarations are used to identify the dates that different jurisdictions implemented various social distancing policies (emergency declarations, school closures, bans on large gatherings, limits on bars, restaurants and other public places, the deployment of severe travel restrictions, and “stay-at-home” or “shelter-in-place” orders). For example, President Trump declared a state of emergency on March 13, 2020, to enhance the federal government response to confront COVID-19. Later in the past spring, at least 316 million people in at least 42 states, the District of Columbia and Puerto Rico were urged to stay home.

Since the late April, all 50 states in the US began to reopen successively, due to the immense pressures of the crippled economy and anxious public. A state is categorized as “reopening” once its stay-at-home order lifts, or once reopening is permitted in at least one primary sector (restaurants, retail stores, personal care businesses), or once reopening is permitted in a combination of smaller sectors. We compiled the dates of executive orders by checking national and state governmental websites, news articles, and press releases. 

### Demographic Characteristics 

In the demographic characteristics category, we consider the factors describing racial, ethnic, sexual, and age structures. These variables are extracted from the [2010 Census](https://data.census.gov/cedsci/table?q=urban\%20rate&hidePreview=false&tid=DECENNIALSF12010.H2&vintage=2010), and the [2010--2018 American Community Survey (ACS) Demographic and Housing Estimates](https://data.census.gov/cedsci/table?q=population\%20density&hidePreview=false&tid=ACSDP1Y2018.DP05&vintage=2018).

Specifically, we include the following six variable

* **AA_PCT**: the percent of the population who identify as African American;

* **HL_PCT**: the percent of the population who identify as Hispanic or Latino;

* **Old_PCT**: the percent of aged people (age >= 65 years);

* **Sex_ratio**: the ratio of male over female;

* **PD_log**: the logrithm of the population density per square mile of land area; 

* **Pop_log**: the logarithm of local population;

* **Mortality**: the five-year (1998-2002) average mortality rate, measured by the total counts of deaths per 100, 000 population in a county.

### Healthcare Infrastructure 

We also incorporate several features related to the healthcare infrastructure at the county level in the datasets, including the percent of persons under 65 years without health insurance, the local government expenditures for health per capita, and total bed counts per 1,000 population.

* **NHIC_PCT**: the percent of persons under 65 years without health insurance

* **EHPC**: the local government expenditures for health per capita;

* **TBed**: the total bed counts per 1,000 population.


### Socioeconomic Status 

We consider diverse socioeconomic factors in the county level datasets. All of these factors collected from [2005--2009 ACS five-year estimates](https://data.census.gov/cedsci/table?q=gini\%20coefficient&hidePreview=false&tid=ACSDT1Y2018.B19083&vintage=2018).

* **Affluence**: social affluence generated by factor analysis from **HighIncome**, **HighEducation**, **WCEmployment** and **MedHU**;

* **HIncome_PCT**: the percent of families with annual incomes higher than $75,000;

* **HEducation_PCT**: the percent of the population aged 25 years or older with a bachelor's degree or higher;

* **MedHU**: the median value of owner-occupied housing units;

* **Disadvantage**: concentrated disadvantage obtained by factor analysis from **HHD_PAI_PCT**, **HHD_F_PCT** and **Unemployment_PCT**;

* **HHD_PAI_PCT**: the percent of the households with public assistance income;

* **HHD_F_PCT**: the percent of households with female householders and no husband present;

* **Unemployment_PCT**: civilian labor force unemployment rate;

* **Gini**: the Gini coefficient, a measure for income inequality and wealth distribution in economics.

### Environmental Factor 

We also collect environmental factors that might affect the spread of epidemics significantly, such as the urban rate and crime rate.

* **UrbanRate**: urban rate; 

* **ViolentCrime**: the total number of violent crimes per 1,000 population;

* **PropertyCrime**: the total number of property crimes per 1,000 population;

* **ResidStability**: the percent of the population residence in the same house for one year and over.

### Mobility 

Another category of factors in the literature that affects the spread of infectious diseases significantly is the mobility; for example, movements of people from neighborhoods. We collect the mobility data from the Bureau of Transportation Statistics. 

* **Number of trips X -- XX**: number of trips by residents greater than X miles and shorter than XX miles. There are 10 different trip ranges: "<= 1", "1 -- 3", "3 -- 5", "5--10", "10 -- 25", "25 -- 50",	"50 -- 100", "100 -- 250", "250 -- 500", and " > 500".

* **Population Stay at Home**: number of residents staying at home, that is, persons who make no trips with a trip end more than one mile away from home. 

### Geographic Information 

The **longitude** and **latitude** of the geographic center for each county in the US are available in Gazetteer Files: https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2019_Gazetteer.


## Data Sets

### Chapter 2
* `I.county`: a 3104 by 328 dataframe with columns `ID`, `County`, `State` and dates from`X2020.12.11` to `X2020.01.22`.

* `pop.county`: a 3142 by 4 dataframe with columns `ID`, `County`, `State` and `population`. Each row of the dataframe stands for one county along with its population.

* `state.long`: a 15925 by 7 dataframe with columns `State`, `Region`, `Division`, `pop`, `DATE`, `Infected` and `Death`. Each row of the dataframe stands for one state on a specific date.

* `I.state`/`I.state.wide`: a 49 by 326 dataframe with columns `State` and dates from`X2020.12.11` to `X2020.01.22`. Each row of the dataframe stands for the time series of infected cases for one state.

* `I.state.long`: a 15925 by 3 dataframe with columns `State`, `DATE` and `Infect`. Each row of the dataframe stands for one state on a specific date.

<!-- * `I.county.top10` -->

<!-- * `I.county.new` -->

<!-- * `I.county.Iowa.new` -->

### Chapter 3

