<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Hybrid Mdels | Statistical Learning of Infectious Disease Data Analytics</title>
  <meta name="description" content="The use of statistical models to understand infectious disease dynamics has a very rich history in epidemiology. This book introduces modern statistical models and state-of-the-art learning methods to analyze infectious disease data. Many of the key approaches, examples and case studies will be presented. The primary emphasis will be interpretation, inference and hands-on data analyses. This course also provides practical concepts and R computing skills to perform infectious disease data analysis and visualization." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Hybrid Mdels | Statistical Learning of Infectious Disease Data Analytics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The use of statistical models to understand infectious disease dynamics has a very rich history in epidemiology. This book introduces modern statistical models and state-of-the-art learning methods to analyze infectious disease data. Many of the key approaches, examples and case studies will be presented. The primary emphasis will be interpretation, inference and hands-on data analyses. This course also provides practical concepts and R computing skills to perform infectious disease data analysis and visualization." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Hybrid Mdels | Statistical Learning of Infectious Disease Data Analytics" />
  
  <meta name="twitter:description" content="The use of statistical models to understand infectious disease dynamics has a very rich history in epidemiology. This book introduces modern statistical models and state-of-the-art learning methods to analyze infectious disease data. Many of the key approaches, examples and case studies will be presented. The primary emphasis will be interpretation, inference and hands-on data analyses. This course also provides practical concepts and R computing skills to perform infectious disease data analysis and visualization." />
  

<meta name="author" content="Lily Wang" />


<meta name="date" content="2021-02-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="NN.html"/>
<link rel="next" href="references-1.html"/>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3.9000/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-sets-used-in-labs-and-exercises"><i class="fa fa-check"></i><b>1.1</b> Data Sets Used in Labs and Exercises</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.2</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i><b>1.3</b> About the Author</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#aims-and-scope-of-this-book"><i class="fa fa-check"></i><b>2.1</b> Aims and Scope of This Book</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#the-structure-of-this-book"><i class="fa fa-check"></i><b>2.2</b> The Structure of This Book</a><ul>
<li class="chapter" data-level="2.2.1" data-path="intro.html"><a href="intro.html#infectious-disease-data"><i class="fa fa-check"></i><b>2.2.1</b> Infectious disease data</a></li>
<li class="chapter" data-level="2.2.2" data-path="intro.html"><a href="intro.html#basic-characteristics-of-the-infection-process"><i class="fa fa-check"></i><b>2.2.2</b> Basic characteristics of the infection process</a></li>
<li class="chapter" data-level="2.2.3" data-path="intro.html"><a href="intro.html#data-visualization"><i class="fa fa-check"></i><b>2.2.3</b> Data visualization</a></li>
<li class="chapter" data-level="2.2.4" data-path="intro.html"><a href="intro.html#modeling-and-forecasting"><i class="fa fa-check"></i><b>2.2.4</b> Modeling and Forecasting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>3</b> Data Wrangling with <code>dplyr</code> and <code>tidyr</code></a><ul>
<li class="chapter" data-level="3.1" data-path="dplyr.html"><a href="dplyr.html#learning-dplyr"><i class="fa fa-check"></i><b>3.1</b> Learning <code>dplyr</code></a><ul>
<li class="chapter" data-level="3.1.1" data-path="dplyr.html"><a href="dplyr.html#tibbles"><i class="fa fa-check"></i><b>3.1.1</b> Tibbles</a></li>
<li class="chapter" data-level="3.1.2" data-path="dplyr.html"><a href="dplyr.html#import-data"><i class="fa fa-check"></i><b>3.1.2</b> Import data</a></li>
<li class="chapter" data-level="3.1.3" data-path="dplyr.html"><a href="dplyr.html#common-dplyr-functions"><i class="fa fa-check"></i><b>3.1.3</b> Common <code>dplyr</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dplyr.html"><a href="dplyr.html#selecting-columns-and-filtering-rows"><i class="fa fa-check"></i><b>3.2</b> Selecting Columns and Filtering Rows</a><ul>
<li class="chapter" data-level="3.2.1" data-path="dplyr.html"><a href="dplyr.html#subset-variables-columns"><i class="fa fa-check"></i><b>3.2.1</b> Subset Variables (Columns)</a></li>
<li class="chapter" data-level="3.2.2" data-path="dplyr.html"><a href="dplyr.html#subset-observations-rows"><i class="fa fa-check"></i><b>3.2.2</b> Subset Observations (Rows)</a></li>
<li class="chapter" data-level="3.2.3" data-path="dplyr.html"><a href="dplyr.html#pipes"><i class="fa fa-check"></i><b>3.2.3</b> Pipes</a></li>
<li class="chapter" data-level="3.2.4" data-path="dplyr.html"><a href="dplyr.html#select-and-order-top-n-entries-by-group-if-grouped-data."><i class="fa fa-check"></i><b>3.2.4</b> Select and order top n entries (by group if grouped data).</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dplyr.html"><a href="dplyr.html#make-new-variables-mutate"><i class="fa fa-check"></i><b>3.3</b> Make New Variables: Mutate</a></li>
<li class="chapter" data-level="3.4" data-path="dplyr.html"><a href="dplyr.html#summarize-data"><i class="fa fa-check"></i><b>3.4</b> Summarize Data</a></li>
<li class="chapter" data-level="3.5" data-path="dplyr.html"><a href="dplyr.html#combine-data-sets"><i class="fa fa-check"></i><b>3.5</b> Combine Data Sets</a><ul>
<li class="chapter" data-level="3.5.1" data-path="dplyr.html"><a href="dplyr.html#the-join-family"><i class="fa fa-check"></i><b>3.5.1</b> The join family</a></li>
<li class="chapter" data-level="3.5.2" data-path="dplyr.html"><a href="dplyr.html#toy-examples-with-joins"><i class="fa fa-check"></i><b>3.5.2</b> Toy examples with joins</a></li>
<li class="chapter" data-level="3.5.3" data-path="dplyr.html"><a href="dplyr.html#practice-with-joins-for-real-data"><i class="fa fa-check"></i><b>3.5.3</b> Practice with joins for real data</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="dplyr.html"><a href="dplyr.html#reshaping-data"><i class="fa fa-check"></i><b>3.6</b> Reshaping Data</a><ul>
<li class="chapter" data-level="3.6.1" data-path="dplyr.html"><a href="dplyr.html#from-wide-to-long"><i class="fa fa-check"></i><b>3.6.1</b> From wide to long</a></li>
<li class="chapter" data-level="3.6.2" data-path="dplyr.html"><a href="dplyr.html#from-long-to-wide"><i class="fa fa-check"></i><b>3.6.2</b> From long to wide</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="dplyr.html"><a href="dplyr.html#exercises"><i class="fa fa-check"></i><b>3.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ggplot2.html"><a href="ggplot2.html"><i class="fa fa-check"></i><b>4</b> Data Visualization with ggplot2</a><ul>
<li class="chapter" data-level="4.1" data-path="ggplot2.html"><a href="ggplot2.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="ggplot2.html"><a href="ggplot2.html#types-of-variables-and-preparation"><i class="fa fa-check"></i><b>4.2</b> Types of Variables and Preparation</a><ul>
<li class="chapter" data-level="4.2.1" data-path="ggplot2.html"><a href="ggplot2.html#types-of-variables"><i class="fa fa-check"></i><b>4.2.1</b> Types of Variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="ggplot2.html"><a href="ggplot2.html#rules-for-graph-designing"><i class="fa fa-check"></i><b>4.2.2</b> Rules for Graph Designing</a></li>
<li class="chapter" data-level="4.2.3" data-path="ggplot2.html"><a href="ggplot2.html#installing-packages-and-loading-data"><i class="fa fa-check"></i><b>4.2.3</b> Installing packages and loading data</a></li>
<li class="chapter" data-level="4.2.4" data-path="ggplot2.html"><a href="ggplot2.html#your-first-scatterplot"><i class="fa fa-check"></i><b>4.2.4</b> Your first scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ggplot2.html"><a href="ggplot2.html#position-scales-and-axes"><i class="fa fa-check"></i><b>4.3</b> Position Scales and Axes</a><ul>
<li class="chapter" data-level="4.3.1" data-path="ggplot2.html"><a href="ggplot2.html#change-the-labels-of-the-axis-using-xlab-and-ylab"><i class="fa fa-check"></i><b>4.3.1</b> Change the labels of the axis using <code>xlab()</code> and <code>ylab()</code></a></li>
<li class="chapter" data-level="4.3.2" data-path="ggplot2.html"><a href="ggplot2.html#change-the-range-of-the-axis-using-xlim-and-ylim"><i class="fa fa-check"></i><b>4.3.2</b> Change the range of the axis using <code>xlim()</code> and <code>ylim()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ggplot2.html"><a href="ggplot2.html#color-scales-and-size-of-geom_points"><i class="fa fa-check"></i><b>4.4</b> Color Scales and Size of <code>geom_points()</code></a><ul>
<li class="chapter" data-level="4.4.1" data-path="ggplot2.html"><a href="ggplot2.html#change-the-color-of-all-points"><i class="fa fa-check"></i><b>4.4.1</b> Change the color of all points</a></li>
<li class="chapter" data-level="4.4.2" data-path="ggplot2.html"><a href="ggplot2.html#color-the-observations-by-the-value-of-a-feature"><i class="fa fa-check"></i><b>4.4.2</b> Color the observations by the value of a feature</a></li>
<li class="chapter" data-level="4.4.3" data-path="ggplot2.html"><a href="ggplot2.html#change-the-color-palette"><i class="fa fa-check"></i><b>4.4.3</b> Change the color palette</a></li>
<li class="chapter" data-level="4.4.4" data-path="ggplot2.html"><a href="ggplot2.html#change-the-size-by-the-value-of-a-feature"><i class="fa fa-check"></i><b>4.4.4</b> Change the size by the value of a feature</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ggplot2.html"><a href="ggplot2.html#individual-geoms"><i class="fa fa-check"></i><b>4.5</b> Individual geoms</a><ul>
<li class="chapter" data-level="4.5.1" data-path="ggplot2.html"><a href="ggplot2.html#histogram"><i class="fa fa-check"></i><b>4.5.1</b> Histogram</a></li>
<li class="chapter" data-level="4.5.2" data-path="ggplot2.html"><a href="ggplot2.html#bar-chart"><i class="fa fa-check"></i><b>4.5.2</b> Bar chart</a></li>
<li class="chapter" data-level="4.5.3" data-path="ggplot2.html"><a href="ggplot2.html#default-bar-chart"><i class="fa fa-check"></i><b>4.5.3</b> Default bar chart</a></li>
<li class="chapter" data-level="4.5.4" data-path="ggplot2.html"><a href="ggplot2.html#bar-chart-with-assigned-value"><i class="fa fa-check"></i><b>4.5.4</b> Bar chart with assigned value</a></li>
<li class="chapter" data-level="4.5.5" data-path="ggplot2.html"><a href="ggplot2.html#legend"><i class="fa fa-check"></i><b>4.5.5</b> Legend</a></li>
<li class="chapter" data-level="4.5.6" data-path="ggplot2.html"><a href="ggplot2.html#boxplots-jittering-and-violin-plots"><i class="fa fa-check"></i><b>4.5.6</b> Boxplots, jittering and violin plots</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ggplot2.html"><a href="ggplot2.html#collective-geoms"><i class="fa fa-check"></i><b>4.6</b> Collective geoms</a><ul>
<li class="chapter" data-level="4.6.1" data-path="ggplot2.html"><a href="ggplot2.html#smoother"><i class="fa fa-check"></i><b>4.6.1</b> Smoother</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ggplot2.html"><a href="ggplot2.html#time-series"><i class="fa fa-check"></i><b>4.7</b> Time Series</a><ul>
<li class="chapter" data-level="4.7.1" data-path="ggplot2.html"><a href="ggplot2.html#basic-line-plots"><i class="fa fa-check"></i><b>4.7.1</b> Basic line plots</a></li>
<li class="chapter" data-level="4.7.2" data-path="ggplot2.html"><a href="ggplot2.html#add-a-second-line"><i class="fa fa-check"></i><b>4.7.2</b> Add a second line</a></li>
<li class="chapter" data-level="4.7.3" data-path="ggplot2.html"><a href="ggplot2.html#add-ribbons"><i class="fa fa-check"></i><b>4.7.3</b> Add ribbons</a></li>
<li class="chapter" data-level="4.7.4" data-path="ggplot2.html"><a href="ggplot2.html#adjust-the-scale-of-time-axis"><i class="fa fa-check"></i><b>4.7.4</b> Adjust the scale of time axis</a></li>
<li class="chapter" data-level="4.7.5" data-path="ggplot2.html"><a href="ggplot2.html#add-annotations"><i class="fa fa-check"></i><b>4.7.5</b> Add annotations</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="ggplot2.html"><a href="ggplot2.html#maps"><i class="fa fa-check"></i><b>4.8</b> Maps</a><ul>
<li class="chapter" data-level="4.8.1" data-path="ggplot2.html"><a href="ggplot2.html#making-a-base-map"><i class="fa fa-check"></i><b>4.8.1</b> Making a base map</a></li>
<li class="chapter" data-level="4.8.2" data-path="ggplot2.html"><a href="ggplot2.html#customizing-choropleth-map"><i class="fa fa-check"></i><b>4.8.2</b> Customizing <code>choropleth</code> map</a></li>
<li class="chapter" data-level="4.8.3" data-path="ggplot2.html"><a href="ggplot2.html#overlay-polygon-maps"><i class="fa fa-check"></i><b>4.8.3</b> Overlay polygon maps</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="ggplot2.html"><a href="ggplot2.html#arranging-plots"><i class="fa fa-check"></i><b>4.9</b> Arranging Plots</a><ul>
<li class="chapter" data-level="4.9.1" data-path="ggplot2.html"><a href="ggplot2.html#facet"><i class="fa fa-check"></i><b>4.9.1</b> Facet</a></li>
<li class="chapter" data-level="4.9.2" data-path="ggplot2.html"><a href="ggplot2.html#combining-plots-using-patchwork-package"><i class="fa fa-check"></i><b>4.9.2</b> Combining plots using <code>patchwork</code> package</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="ggplot2.html"><a href="ggplot2.html#output"><i class="fa fa-check"></i><b>4.10</b> Output</a><ul>
<li class="chapter" data-level="4.10.1" data-path="ggplot2.html"><a href="ggplot2.html#save-in-figure-format"><i class="fa fa-check"></i><b>4.10.1</b> Save in figure format</a></li>
<li class="chapter" data-level="4.10.2" data-path="ggplot2.html"><a href="ggplot2.html#save-in-rds-format"><i class="fa fa-check"></i><b>4.10.2</b> Save in RDS format</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="ggplot2.html"><a href="ggplot2.html#exercises-1"><i class="fa fa-check"></i><b>4.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotly.html"><a href="plotly.html"><i class="fa fa-check"></i><b>5</b> Interactive Visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="plotly.html"><a href="plotly.html#an-introduction"><i class="fa fa-check"></i><b>5.1</b> An Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="plotly.html"><a href="plotly.html#creating-plotly-objects"><i class="fa fa-check"></i><b>5.2</b> Creating Plotly Objects</a><ul>
<li class="chapter" data-level="5.2.1" data-path="plotly.html"><a href="plotly.html#using-plot_ly-to-create-a-plotly-object"><i class="fa fa-check"></i><b>5.2.1</b> Using <code>plot_ly()</code> to create a plotly object</a></li>
<li class="chapter" data-level="5.2.2" data-path="plotly.html"><a href="plotly.html#use-dplyr-verbs-to-modify-data"><i class="fa fa-check"></i><b>5.2.2</b> Use <code>dplyr</code> verbs to modify data</a></li>
<li class="chapter" data-level="5.2.3" data-path="plotly.html"><a href="plotly.html#using-ggplotly-to-create-a-plotly-object"><i class="fa fa-check"></i><b>5.2.3</b> Using <code>ggplotly()</code> to create a <code>plotly</code> object</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="plotly.html"><a href="plotly.html#scatterplots-and-line-plots"><i class="fa fa-check"></i><b>5.3</b> Scatterplots and Line Plots</a><ul>
<li class="chapter" data-level="5.3.1" data-path="plotly.html"><a href="plotly.html#make-a-scatterplot"><i class="fa fa-check"></i><b>5.3.1</b> Make a scatterplot</a></li>
<li class="chapter" data-level="5.3.2" data-path="plotly.html"><a href="plotly.html#markers"><i class="fa fa-check"></i><b>5.3.2</b> Markers</a></li>
<li class="chapter" data-level="5.3.3" data-path="plotly.html"><a href="plotly.html#a-single-time-series-plot"><i class="fa fa-check"></i><b>5.3.3</b> A single time series plot</a></li>
<li class="chapter" data-level="5.3.4" data-path="plotly.html"><a href="plotly.html#hover-text-and-template"><i class="fa fa-check"></i><b>5.3.4</b> Hover text and template</a></li>
<li class="chapter" data-level="5.3.5" data-path="plotly.html"><a href="plotly.html#multiple-time-series-plots"><i class="fa fa-check"></i><b>5.3.5</b> Multiple time series plots</a></li>
<li class="chapter" data-level="5.3.6" data-path="plotly.html"><a href="plotly.html#more-features-about-the-lines"><i class="fa fa-check"></i><b>5.3.6</b> More features about the lines</a></li>
<li class="chapter" data-level="5.3.7" data-path="plotly.html"><a href="plotly.html#add-ribbons-1"><i class="fa fa-check"></i><b>5.3.7</b> Add ribbons</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="plotly.html"><a href="plotly.html#pie-charts"><i class="fa fa-check"></i><b>5.4</b> Pie Charts</a></li>
<li class="chapter" data-level="5.5" data-path="plotly.html"><a href="plotly.html#animation"><i class="fa fa-check"></i><b>5.5</b> Animation</a><ul>
<li class="chapter" data-level="5.5.1" data-path="plotly.html"><a href="plotly.html#an-animation-of-the-evolution-of-infected-vs.-death-count"><i class="fa fa-check"></i><b>5.5.1</b> An animation of the evolution of infected vs. death count</a></li>
<li class="chapter" data-level="5.5.2" data-path="plotly.html"><a href="plotly.html#an-animation-of-the-state-level-time-series-plot-of-infected-count"><i class="fa fa-check"></i><b>5.5.2</b> An animation of the state-level time series plot of infected count</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="plotly.html"><a href="plotly.html#saving-html"><i class="fa fa-check"></i><b>5.6</b> Saving HTML</a><ul>
<li class="chapter" data-level="5.6.1" data-path="plotly.html"><a href="plotly.html#save-as-a-standalone-html-file"><i class="fa fa-check"></i><b>5.6.1</b> Save as a standalone HTML file</a></li>
<li class="chapter" data-level="5.6.2" data-path="plotly.html"><a href="plotly.html#save-as-non-selfcontained-html-file"><i class="fa fa-check"></i><b>5.6.2</b> Save as non-selfcontained HTML file</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="plotly.html"><a href="plotly.html#exercises-2"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>6</b> R Shiny</a><ul>
<li class="chapter" data-level="6.1" data-path="shiny.html"><a href="shiny.html#embedding-plotly-in-shiny"><i class="fa fa-check"></i><b>6.1</b> Embedding plotly in Shiny</a><ul>
<li class="chapter" data-level="6.1.1" data-path="shiny.html"><a href="shiny.html#your-first-shiny-app"><i class="fa fa-check"></i><b>6.1.1</b> Your first shiny app</a></li>
<li class="chapter" data-level="6.1.2" data-path="shiny.html"><a href="shiny.html#useful-input-widgets"><i class="fa fa-check"></i><b>6.1.2</b> Useful input widgets</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="shiny.html"><a href="shiny.html#rendering-plotly-inside-shiny"><i class="fa fa-check"></i><b>6.2</b> Rendering plotly Inside Shiny</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="map.html"><a href="map.html"><i class="fa fa-check"></i><b>7</b> Interactive Geospatial Visualization</a><ul>
<li class="chapter" data-level="7.1" data-path="map.html"><a href="map.html#an-introduction-to-leaflet"><i class="fa fa-check"></i><b>7.1</b> An Introduction to Leaflet</a><ul>
<li class="chapter" data-level="7.1.1" data-path="map.html"><a href="map.html#features-and-installation"><i class="fa fa-check"></i><b>7.1.1</b> Features and installation</a></li>
<li class="chapter" data-level="7.1.2" data-path="map.html"><a href="map.html#basic-usage"><i class="fa fa-check"></i><b>7.1.2</b> Basic Usage</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="map.html"><a href="map.html#the-data-object"><i class="fa fa-check"></i><b>7.2</b> The Data Object</a></li>
<li class="chapter" data-level="7.3" data-path="map.html"><a href="map.html#choropleth-map"><i class="fa fa-check"></i><b>7.3</b> Choropleth map</a><ul>
<li class="chapter" data-level="7.3.1" data-path="map.html"><a href="map.html#create-a-base-map"><i class="fa fa-check"></i><b>7.3.1</b> Create a base map</a></li>
<li class="chapter" data-level="7.3.2" data-path="map.html"><a href="map.html#color-the-map"><i class="fa fa-check"></i><b>7.3.2</b> Color the map</a></li>
<li class="chapter" data-level="7.3.3" data-path="map.html"><a href="map.html#interactive-map"><i class="fa fa-check"></i><b>7.3.3</b> Interactive map</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="map.html"><a href="map.html#legend-1"><i class="fa fa-check"></i><b>7.4</b> Legend</a><ul>
<li class="chapter" data-level="7.4.1" data-path="map.html"><a href="map.html#classification-schemes"><i class="fa fa-check"></i><b>7.4.1</b> Classification schemes</a></li>
<li class="chapter" data-level="7.4.2" data-path="map.html"><a href="map.html#mapping-variables-to-colors"><i class="fa fa-check"></i><b>7.4.2</b> Mapping variables to colors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="map.html"><a href="map.html#an-example-of-county-level-map"><i class="fa fa-check"></i><b>7.5</b> An Example of County-level Map</a></li>
<li class="chapter" data-level="7.6" data-path="map.html"><a href="map.html#spot-maps"><i class="fa fa-check"></i><b>7.6</b> Spot Maps</a></li>
<li class="chapter" data-level="7.7" data-path="map.html"><a href="map.html#integrating-leaflet-with-r-shiny"><i class="fa fa-check"></i><b>7.7</b> Integrating Leaflet with R Shiny</a></li>
<li class="chapter" data-level="7.8" data-path="map.html"><a href="map.html#exercises-3"><i class="fa fa-check"></i><b>7.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modeling.html"><a href="modeling.html"><i class="fa fa-check"></i><b>8</b> Epidemic Modeling</a><ul>
<li class="chapter" data-level="8.1" data-path="modeling.html"><a href="modeling.html#an-introduction-to-epidemic-modeling"><i class="fa fa-check"></i><b>8.1</b> An Introduction to Epidemic Modeling</a></li>
<li class="chapter" data-level="8.2" data-path="modeling.html"><a href="modeling.html#compartment-models"><i class="fa fa-check"></i><b>8.2</b> Compartment Models</a><ul>
<li class="chapter" data-level="8.2.1" data-path="modeling.html"><a href="modeling.html#a-simple-sis-model-a-model-for-diseases-with-no-immunity"><i class="fa fa-check"></i><b>8.2.1</b> A Simple SIS Model (A Model for Diseases with No Immunity)</a></li>
<li class="chapter" data-level="8.2.2" data-path="modeling.html"><a href="modeling.html#an-sir-model"><i class="fa fa-check"></i><b>8.2.2</b> An SIR Model</a></li>
<li class="chapter" data-level="8.2.3" data-path="modeling.html"><a href="modeling.html#an-sir-model-with-births-and-deaths"><i class="fa fa-check"></i><b>8.2.3</b> An SIR model with births and deaths</a></li>
<li class="chapter" data-level="8.2.4" data-path="modeling.html"><a href="modeling.html#sir-parameter-estimation"><i class="fa fa-check"></i><b>8.2.4</b> SIR parameter estimation</a></li>
<li class="chapter" data-level="8.2.5" data-path="modeling.html"><a href="modeling.html#implementation-of-parameter-estimation-in-r"><i class="fa fa-check"></i><b>8.2.5</b> Implementation of parameter estimation in R</a></li>
<li class="chapter" data-level="8.2.6" data-path="modeling.html"><a href="modeling.html#basic-reproduction-number"><i class="fa fa-check"></i><b>8.2.6</b> Basic Reproduction Number</a></li>
<li class="chapter" data-level="8.2.7" data-path="modeling.html"><a href="modeling.html#seir-model"><i class="fa fa-check"></i><b>8.2.7</b> SEIR Model</a></li>
<li class="chapter" data-level="8.2.8" data-path="modeling.html"><a href="modeling.html#herd-immunity"><i class="fa fa-check"></i><b>8.2.8</b> Herd Immunity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Regression Modeling</a><ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#principles-of-regression-modeling"><i class="fa fa-check"></i><b>9.1</b> Principles of Regression Modeling</a><ul>
<li class="chapter" data-level="9.1.1" data-path="regression.html"><a href="regression.html#linear-regression"><i class="fa fa-check"></i><b>9.1.1</b> Linear regression</a></li>
<li class="chapter" data-level="9.1.2" data-path="regression.html"><a href="regression.html#poisson-regression"><i class="fa fa-check"></i><b>9.1.2</b> Poisson regression</a></li>
<li class="chapter" data-level="9.1.3" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>9.1.3</b> Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#area-level-data"><i class="fa fa-check"></i><b>9.2</b> Area-level Data</a></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#variable-selection"><i class="fa fa-check"></i><b>9.3</b> Variable Selection</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="timeseries.html"><a href="timeseries.html"><i class="fa fa-check"></i><b>10</b> Time Series Analysis of Infectious Disease Data</a><ul>
<li class="chapter" data-level="10.1" data-path="timeseries.html"><a href="timeseries.html#datasets-and-r-packages"><i class="fa fa-check"></i><b>10.1</b> Datasets and R Packages</a></li>
<li class="chapter" data-level="10.2" data-path="timeseries.html"><a href="timeseries.html#time-series-plots"><i class="fa fa-check"></i><b>10.2</b> Time series plots</a><ul>
<li class="chapter" data-level="10.2.1" data-path="timeseries.html"><a href="timeseries.html#tsibble-objects"><i class="fa fa-check"></i><b>10.2.1</b> “tsibble” objects</a></li>
<li class="chapter" data-level="10.2.2" data-path="timeseries.html"><a href="timeseries.html#working-with-tsibble-objects"><i class="fa fa-check"></i><b>10.2.2</b> Working with “tsibble” objects</a></li>
<li class="chapter" data-level="10.2.3" data-path="timeseries.html"><a href="timeseries.html#drawing-time-series-plots"><i class="fa fa-check"></i><b>10.2.3</b> Drawing time series plots</a></li>
<li class="chapter" data-level="10.2.4" data-path="timeseries.html"><a href="timeseries.html#objectives-of-time-series-analysis"><i class="fa fa-check"></i><b>10.2.4</b> Objectives of Time Series Analysis</a></li>
<li class="chapter" data-level="10.2.5" data-path="timeseries.html"><a href="timeseries.html#autocorrelation"><i class="fa fa-check"></i><b>10.2.5</b> Autocorrelation</a></li>
<li class="chapter" data-level="10.2.6" data-path="timeseries.html"><a href="timeseries.html#autocorrelation-1"><i class="fa fa-check"></i><b>10.2.6</b> Autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="timeseries.html"><a href="timeseries.html#time-series-decomposition"><i class="fa fa-check"></i><b>10.3</b> Time Series Decomposition</a></li>
<li class="chapter" data-level="10.4" data-path="timeseries.html"><a href="timeseries.html#simple-time-series-forecasting-approaches"><i class="fa fa-check"></i><b>10.4</b> Simple Time Series Forecasting Approaches</a><ul>
<li class="chapter" data-level="10.4.1" data-path="timeseries.html"><a href="timeseries.html#average-method"><i class="fa fa-check"></i><b>10.4.1</b> Average method</a></li>
<li class="chapter" data-level="10.4.2" data-path="timeseries.html"><a href="timeseries.html#random-walk-forecasts"><i class="fa fa-check"></i><b>10.4.2</b> Random walk forecasts</a></li>
<li class="chapter" data-level="10.4.3" data-path="timeseries.html"><a href="timeseries.html#seasonal-random-walk-forecasts"><i class="fa fa-check"></i><b>10.4.3</b> Seasonal random walk forecasts</a></li>
<li class="chapter" data-level="10.4.4" data-path="timeseries.html"><a href="timeseries.html#random-walk-with-drift-method"><i class="fa fa-check"></i><b>10.4.4</b> Random walk with drift method</a></li>
<li class="chapter" data-level="10.4.5" data-path="timeseries.html"><a href="timeseries.html#combining-the-forecasting-results"><i class="fa fa-check"></i><b>10.4.5</b> Combining the forecasting results</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="timeseries.html"><a href="timeseries.html#methods-for-estimating-the-trend"><i class="fa fa-check"></i><b>10.5</b> Methods for Estimating the Trend</a></li>
<li class="chapter" data-level="10.6" data-path="timeseries.html"><a href="timeseries.html#arma-models"><i class="fa fa-check"></i><b>10.6</b> ARMA Models</a><ul>
<li class="chapter" data-level="10.6.1" data-path="timeseries.html"><a href="timeseries.html#simple-examples-of-arma-models"><i class="fa fa-check"></i><b>10.6.1</b> Simple Examples of ARMA Models</a></li>
<li class="chapter" data-level="10.6.2" data-path="timeseries.html"><a href="timeseries.html#arima"><i class="fa fa-check"></i><b>10.6.2</b> ARIMA</a></li>
<li class="chapter" data-level="10.6.3" data-path="timeseries.html"><a href="timeseries.html#seasonal-arima-model"><i class="fa fa-check"></i><b>10.6.3</b> Seasonal ARIMA model</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="timeseries.html"><a href="timeseries.html#model-comparison"><i class="fa fa-check"></i><b>10.7</b> Model Comparison</a></li>
<li class="chapter" data-level="10.8" data-path="timeseries.html"><a href="timeseries.html#ensuring-forecasts-stay-within-limits"><i class="fa fa-check"></i><b>10.8</b> Ensuring forecasts stay within limits</a><ul>
<li class="chapter" data-level="10.8.1" data-path="timeseries.html"><a href="timeseries.html#positive-forecasts"><i class="fa fa-check"></i><b>10.8.1</b> Positive forecasts</a></li>
<li class="chapter" data-level="10.8.2" data-path="timeseries.html"><a href="timeseries.html#forecasts-constrained-to-an-interval"><i class="fa fa-check"></i><b>10.8.2</b> Forecasts constrained to an interval</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="timeseries.html"><a href="timeseries.html#prediction-intervals-for-aggregates"><i class="fa fa-check"></i><b>10.9</b> Prediction intervals for aggregates</a></li>
<li class="chapter" data-level="10.10" data-path="timeseries.html"><a href="timeseries.html#exercises-4"><i class="fa fa-check"></i><b>10.10</b> Exercises</a></li>
<li class="chapter" data-level="10.11" data-path="timeseries.html"><a href="timeseries.html#references"><i class="fa fa-check"></i><b>10.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="NN.html"><a href="NN.html"><i class="fa fa-check"></i><b>11</b> Neural Networks</a><ul>
<li class="chapter" data-level="11.1" data-path="NN.html"><a href="NN.html#a-single-neuron"><i class="fa fa-check"></i><b>11.1</b> A Single Neuron</a></li>
<li class="chapter" data-level="11.2" data-path="NN.html"><a href="NN.html#neural-network-structure"><i class="fa fa-check"></i><b>11.2</b> Neural Network Structure</a><ul>
<li class="chapter" data-level="11.2.1" data-path="NN.html"><a href="NN.html#forward-propagation"><i class="fa fa-check"></i><b>11.2.1</b> Forward propagation</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="NN.html"><a href="NN.html#overfitting"><i class="fa fa-check"></i><b>11.3</b> Overfitting</a></li>
<li class="chapter" data-level="11.4" data-path="NN.html"><a href="NN.html#neural-network-auto-regressive-nnar-models"><i class="fa fa-check"></i><b>11.4</b> Neural Network Auto-Regressive (NNAR) models</a></li>
<li class="chapter" data-level="11.5" data-path="NN.html"><a href="NN.html#covid-19-forecasting"><i class="fa fa-check"></i><b>11.5</b> COVID-19 Forecasting</a></li>
<li class="chapter" data-level="11.6" data-path="NN.html"><a href="NN.html#box-cox-transformations"><i class="fa fa-check"></i><b>11.6</b> Box-Cox transformations</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ensemble.html"><a href="ensemble.html"><i class="fa fa-check"></i><b>12</b> Hybrid Mdels</a><ul>
<li class="chapter" data-level="12.1" data-path="ensemble.html"><a href="ensemble.html#ensembling-time-series-models"><i class="fa fa-check"></i><b>12.1</b> Ensembling Time Series Models</a></li>
<li class="chapter" data-level="12.2" data-path="ensemble.html"><a href="ensemble.html#model-diagnostics"><i class="fa fa-check"></i><b>12.2</b> Model Diagnostics</a></li>
<li class="chapter" data-level="12.3" data-path="ensemble.html"><a href="ensemble.html#forecasting"><i class="fa fa-check"></i><b>12.3</b> Forecasting</a><ul>
<li class="chapter" data-level="12.3.1" data-path="ensemble.html"><a href="ensemble.html#perform-cross-validation-on-a-time-series"><i class="fa fa-check"></i><b>12.3.1</b> Perform cross validation on a time series</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ensemble.html"><a href="ensemble.html#weights-selection-using-cross-validation"><i class="fa fa-check"></i><b>12.4</b> Weights Selection Using Cross Validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a></li>
<li class="chapter" data-level="13" data-path="appendix-a.html"><a href="appendix-a.html"><i class="fa fa-check"></i><b>13</b> Appendix A</a><ul>
<li class="chapter" data-level="13.1" data-path="appendix-a.html"><a href="appendix-a.html#r-introduction-and-preliminaries"><i class="fa fa-check"></i><b>13.1</b> R Introduction and Preliminaries</a><ul>
<li class="chapter" data-level="13.1.1" data-path="appendix-a.html"><a href="appendix-a.html#the-r-environment-and-language"><i class="fa fa-check"></i><b>13.1.1</b> The R Environment and Language</a></li>
<li class="chapter" data-level="13.1.2" data-path="appendix-a.html"><a href="appendix-a.html#r-and-statistics"><i class="fa fa-check"></i><b>13.1.2</b> R and Statistics</a></li>
<li class="chapter" data-level="13.1.3" data-path="appendix-a.html"><a href="appendix-a.html#obtaining-r-and-installation"><i class="fa fa-check"></i><b>13.1.3</b> Obtaining R and installation</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="appendix-a.html"><a href="appendix-a.html#starting-r"><i class="fa fa-check"></i><b>13.2</b> Starting R</a><ul>
<li class="chapter" data-level="13.2.1" data-path="appendix-a.html"><a href="appendix-a.html#description-of-three-panels-in-user-interface"><i class="fa fa-check"></i><b>13.2.1</b> Description of three panels in user interface</a></li>
<li class="chapter" data-level="13.2.2" data-path="appendix-a.html"><a href="appendix-a.html#r-help"><i class="fa fa-check"></i><b>13.2.2</b> R help</a></li>
<li class="chapter" data-level="13.2.3" data-path="appendix-a.html"><a href="appendix-a.html#some-mathematical-expressions"><i class="fa fa-check"></i><b>13.2.3</b> Some mathematical expressions</a></li>
<li class="chapter" data-level="13.2.4" data-path="appendix-a.html"><a href="appendix-a.html#r-packages"><i class="fa fa-check"></i><b>13.2.4</b> R Packages</a></li>
<li class="chapter" data-level="13.2.5" data-path="appendix-a.html"><a href="appendix-a.html#creating-a-project-and-setting-working-directory"><i class="fa fa-check"></i><b>13.2.5</b> Creating a project and setting working directory</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="appendix-a.html"><a href="appendix-a.html#exportimport-data"><i class="fa fa-check"></i><b>13.3</b> Export/Import Data</a><ul>
<li class="chapter" data-level="13.3.1" data-path="appendix-a.html"><a href="appendix-a.html#data-export"><i class="fa fa-check"></i><b>13.3.1</b> Data Export</a></li>
<li class="chapter" data-level="13.3.2" data-path="appendix-a.html"><a href="appendix-a.html#data-import"><i class="fa fa-check"></i><b>13.3.2</b> Data Import</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="appendix-b.html"><a href="appendix-b.html"><i class="fa fa-check"></i><b>14</b> Appendix B</a><ul>
<li class="chapter" data-level="14.1" data-path="appendix-b.html"><a href="appendix-b.html#epidemic-data"><i class="fa fa-check"></i><b>14.1</b> Epidemic Data</a><ul>
<li class="chapter" data-level="14.1.1" data-path="appendix-b.html"><a href="appendix-b.html#state-level"><i class="fa fa-check"></i><b>14.1.1</b> State level</a></li>
<li class="chapter" data-level="14.1.2" data-path="appendix-b.html"><a href="appendix-b.html#county-level"><i class="fa fa-check"></i><b>14.1.2</b> County level</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="appendix-b.html"><a href="appendix-b.html#other-factors"><i class="fa fa-check"></i><b>14.2</b> Other Factors</a><ul>
<li class="chapter" data-level="14.2.1" data-path="appendix-b.html"><a href="appendix-b.html#policy-data"><i class="fa fa-check"></i><b>14.2.1</b> Policy Data</a></li>
<li class="chapter" data-level="14.2.2" data-path="appendix-b.html"><a href="appendix-b.html#demographic-characteristics"><i class="fa fa-check"></i><b>14.2.2</b> Demographic Characteristics</a></li>
<li class="chapter" data-level="14.2.3" data-path="appendix-b.html"><a href="appendix-b.html#healthcare-infrastructure"><i class="fa fa-check"></i><b>14.2.3</b> Healthcare Infrastructure</a></li>
<li class="chapter" data-level="14.2.4" data-path="appendix-b.html"><a href="appendix-b.html#socioeconomic-status"><i class="fa fa-check"></i><b>14.2.4</b> Socioeconomic Status</a></li>
<li class="chapter" data-level="14.2.5" data-path="appendix-b.html"><a href="appendix-b.html#environmental-factor"><i class="fa fa-check"></i><b>14.2.5</b> Environmental Factor</a></li>
<li class="chapter" data-level="14.2.6" data-path="appendix-b.html"><a href="appendix-b.html#mobility"><i class="fa fa-check"></i><b>14.2.6</b> Mobility</a></li>
<li class="chapter" data-level="14.2.7" data-path="appendix-b.html"><a href="appendix-b.html#geographic-information"><i class="fa fa-check"></i><b>14.2.7</b> Geographic Information</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="appendix-b.html"><a href="appendix-b.html#data-sets"><i class="fa fa-check"></i><b>14.3</b> Data Sets</a><ul>
<li class="chapter" data-level="14.3.1" data-path="appendix-b.html"><a href="appendix-b.html#chapter-2"><i class="fa fa-check"></i><b>14.3.1</b> Chapter 2</a></li>
<li class="chapter" data-level="14.3.2" data-path="appendix-b.html"><a href="appendix-b.html#chapter-3"><i class="fa fa-check"></i><b>14.3.2</b> Chapter 3</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Learning of Infectious Disease Data Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ensemble" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> Hybrid Mdels</h1>
<p>In the previous chapters, we introduced some time series models, an autoregressive model (ARIMA), an exponential smoothing state space model (ETS), a neural network autoregression model (NNAR).</p>
<p>Hybrid models are identified by using the <code>hybridModel</code> function included in the package <a href="https://cran.r-project.org/web/packages/forecastHybrid/forecastHybrid.pdf">forecastHybrid</a> (in R environment).</p>
<p><strong>Installation</strong></p>
<p>The stable release of the package is hosted on CRAN and can be installed as usual.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># install.packages(&quot;forecastHybrid&quot;)</span>
<span class="co"># Load the package</span>
<span class="kw">library</span>(forecastHybrid)</code></pre></div>
<div id="ensembling-time-series-models" class="section level2">
<h2><span class="header-section-number">12.1</span> Ensembling Time Series Models</h2>
<p>In statistics and machine learning, ensemble methods use multiple forecasting algorithms to improve the predictive performance. Ensemble forecasting can overcome accuracy of simple prediction and to avoid possible overfit. The idea is that, when there is much uncertainty in finding the best model as is the case in many applications, combining may reduce the instability of the forecast and therefore improve prediction accuracy.</p>
<p>In a linear combination technique, the combined forecast for the associated time series is calculated through a linear function of the individual forecasts from the contributing models. Let, <span class="math inline">\(\{y_1, y_2, \ldots, y_n\}\)</span> be the actual time series, which is to be forecasted using <span class="math inline">\(K\)</span> different models and <span class="math inline">\(\{\hat{y}_{n+1}^{(k)}, \hat{y}_{n+2}^{(k)}, \ldots, \hat{y}_{h}^{(k)}\}\)</span> be its forecast obtained from the <span class="math inline">\(k\)</span>th model (<span class="math inline">\(k=1, 2,\ldots, K\)</span>). Then, a linear combination of these <span class="math inline">\(K\)</span> forecasted series of the original time series produces <span class="math inline">\(\{\hat{y}_{n+1}^{*}, \hat{y}_{n+2}^{*}, \ldots, \hat{y}_{h}^{*}\}\)</span>, where <span class="math display">\[
\hat{y}_{n+j}^{*}=f\left(\hat{y}_{n+j}^{(1)},\ldots,\hat{y}_{n+j}^{(K)}\right)
\]</span> for <span class="math inline">\(j=1,2,\ldots,h\)</span>. If <span class="math inline">\(f\)</span> is some linear function, then we have <span class="math display">\[
\hat{y}_{n+j}^{*}=w_1\hat{y}_{n+j}^{(1)}+w_2\hat{y}_{n+j}^{(2)}+\cdots+w_K\hat{y}_{n+j}^{(K)}
=\sum_{k=1}^{K}w_k\hat{y}_{n+j}^{(k)}, 
\]</span> for <span class="math inline">\(j=1,2,\ldots,h\)</span>. Here, <span class="math inline">\(w_k\)</span> is the weight assigned to the <span class="math inline">\(k\)</span>th forecasting method. To ensure unbiasedness, it is often assumed that the weights add up to unity. Some widely used linear combination techniques are briefly described below:</p>
<ul>
<li>In the simple average, all models are assigned equal weights, i.e., <span class="math inline">\(w_k=1⁄K\)</span>, for <span class="math inline">\(k=1, 2,\ldots, K\)</span>.</li>
<li>In the trimmed average, individual forecasts are combined by a simple arithmetic mean, excluding the worst performing <span class="math inline">\(\alpha\)</span>% of the models. A trimming of 10% ~ 30% is usually recommended.</li>
<li>In the Winsorized average, the <span class="math inline">\(m\)</span> smallest and <span class="math inline">\(m\)</span> largest forecasts are selected and respectively set as the <span class="math inline">\((m+1)\)</span>th smallest and <span class="math inline">\((m+1)\)</span>th largest forecasts.</li>
<li>In the median-based combining, the combination function <span class="math inline">\(f\)</span> is the median of the individual forecasts. Median is sometimes preferred over simple average as it is less sensitive to extreme values.</li>
<li>In the error-based combining, the weight to each model is assigned to be the inverse of the past forecast error (e.g. MSE, MAE, MAPE, etc.) of the corresponding model.</li>
</ul>
<p>The <code>hybridModel</code> function in the “forecastHybrid” R package ensembles forecasts in R combining approaches from the 'forecast' package. Forecasts generated from the following models:</p>
<ul>
<li><p><code>auto.arima()</code>: the best ARIMA model according to either AIC, AICc or BIC value;</p></li>
<li><p><code>ets()</code>: exponential smoothing state space model;</p></li>
<li><p><code>stlm()</code>: applies an STL decomposition, and models the seasonally adjusted data using the model passed as modelfunction or specified using method;</p></li>
<li><p><code>nnetar()</code>: feed-forward neural networks with a single hidden layer and lagged inputs;</p></li>
<li><p><code>tbats()</code>: TBATS model (exponential smoothing state space model with Box-Cox transformation, ARMA errors, trend and seasonal components) proposed by <span class="citation">De Livera, Hyndman, and Snyder (<a href="#ref-de2011forecasting">2011</a>)</span>;</p></li>
<li><p><code>thetaf()</code>: the theta method proposed by <span class="citation">Assimakopoulos and Nikolopoulos (<a href="#ref-assimakopoulos2000theta">2000</a>)</span>, which is equivalent to simple exponential smoothing with drift.</p></li>
<li><p><code>snaive()</code>: Seasonal naive method (random walk method)</p></li>
</ul>
<p>These models can be combined with equal weights, weights based on in-sample errors introduced by <span class="citation">Bates and Granger (<a href="#ref-bates1969combination">1969</a>)</span> or cross-validated weights. Cross validation for time series data with user-supplied models and forecasting functions is also supported to evaluate model accuracy.</p>
<p>We consider the daily new death count for Forida. To use the “forecastHybrid” package, it is better to store the time series as a “ts” object in R. Let us consider the time series of daily new death counts for Florida, and we first turn this into a “ts” object using the <code>ts()</code> function. Since we have observed the 7-day cycle for this data, we can simply add a <code>frequency = 7</code> argument.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(slid)
<span class="kw">library</span>(dplyr)
<span class="kw">data</span>(state.ts)

Florida.ts &lt;-<span class="st"> </span>state.ts <span class="op">%&gt;%</span>
<span class="st">    </span>dplyr<span class="op">::</span><span class="kw">filter</span>(State <span class="op">==</span><span class="st"> &quot;Florida&quot;</span>)  

y &lt;-<span class="st"> </span><span class="kw">ts</span>(Florida.ts<span class="op">$</span>Y.Death, <span class="dt">start =</span> <span class="dv">2020</span><span class="op">-</span><span class="dv">01</span><span class="op">-</span><span class="dv">23</span>, <span class="dt">frequency =</span> <span class="dv">7</span>)</code></pre></div>
<p>Using the default setting, we simply apply the <code>hybridModel()</code> function, and obtain the combined forecast from <code>auto.arima</code>, <code>ets</code>, <code>thetam</code>, <code>nnetar</code>, <code>stlm</code>, and <code>tbats</code> model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hmod &lt;-<span class="st"> </span><span class="kw">hybridModel</span>(y)
<span class="kw">forecast</span>(hmod)</code></pre></div>
<pre><code>##          Point Forecast    Lo 80    Hi 80      Lo 95
## 2042.286      106.59821 59.99658 154.8136  39.379958
## 2042.429       92.79875 25.58865 136.8427   4.158083
## 2042.571      104.66484 16.99737 149.2371  -4.861073
## 2042.714      132.91459 76.29264 177.2457  55.328106
## 2042.857      128.86821 66.55646 176.3123  45.370109
## 2043.000      133.53789 72.11097 182.2055  50.721112
## 2043.143      145.27774 76.98625 213.7300  53.494111
## 2043.286      127.33009 56.08554 202.2511  32.202438
## 2043.429      109.45873 21.00009 180.0201  -3.267690
## 2043.571      122.95030 12.40980 218.9806 -12.236645
## 2043.714      149.76991 72.15436 236.0417  46.834814
## 2043.857      143.77561 62.19004 224.8698  36.608705
## 2044.000      148.34727 67.52823 231.8187  41.706667
## 2044.143      157.04804 73.45265 248.4459  47.346402
##             Hi 95
## 2042.286 174.3183
## 2042.429 156.7485
## 2042.571 169.5050
## 2042.714 194.6245
## 2042.857 192.1269
## 2043.000 203.3384
## 2043.143 215.3923
## 2043.286 204.3949
## 2043.429 182.9325
## 2043.571 221.2806
## 2043.714 238.1171
## 2043.857 226.8261
## 2044.000 234.0601
## 2044.143 250.3336</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">forecast</span>(hmod), <span class="dt">xlab =</span> <span class="st">&quot;Days&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Daily new deaths&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Ensembled forecast from different models&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:hmod1"></span>
<img src="bookdown-demo_files/figure-html/hmod1-1.png" alt="Forecast from auto.arima, ets, thetam, nnetar, stlm, and tbats model." width="672" />
<p class="caption">
Figure 12.1: Forecast from auto.arima, ets, thetam, nnetar, stlm, and tbats model.
</p>
</div>
<p>The individual component models are stored inside the <code>hybridModel</code> objects and be can viewed in their respective slots, and all the regular methods from the <code>forecast</code> package could be applied to these individual component models.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#View the individual models </span>
hmod<span class="op">$</span>auto.arima</code></pre></div>
<pre><code>## Series: y 
## ARIMA(1,0,1)(0,1,1)[7] 
## 
## Coefficients:
##          ar1      ma1     sma1
##       0.9627  -0.7927  -0.5724
## s.e.  0.0198   0.0396   0.0614
## 
## sigma^2 estimated as 883.9:  log likelihood=-1524.9
## AIC=3057.8   AICc=3057.93   BIC=3072.83</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># See forecasts from the auto.arima model</span>
<span class="kw">plot</span>(<span class="kw">forecast</span>(hmod<span class="op">$</span>auto.arima), <span class="dt">xlab =</span> <span class="st">&quot;Days&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Daily new deaths&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:hmod2"></span>
<img src="bookdown-demo_files/figure-html/hmod2-1.png" alt="Forecast from auto.arima model." width="672" />
<p class="caption">
Figure 12.2: Forecast from auto.arima model.
</p>
</div>
</div>
<div id="model-diagnostics" class="section level2">
<h2><span class="header-section-number">12.2</span> Model Diagnostics</h2>
<p>The <code>hybridModel()</code> function produces an S3 object of class forecastHybrid.</p>
<p>The <code>print()</code> and <code>summary()</code> methods print information about the ensemble model including the weights assigned to each individual component model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(hmod) 
## Hybrid forecast model comprised of the following models: auto.arima, ets, thetam, nnetar, stlm, tbats
## ############
## auto.arima with weight 0.167 
## ############
## ets with weight 0.167 
## ############
## thetam with weight 0.167 
## ############
## nnetar with weight 0.167 
## ############
## stlm with weight 0.167 
## ############
## tbats with weight 0.167
<span class="kw">summary</span>(hmod)
##            Length Class          Mode     
## auto.arima  18    forecast_ARIMA list     
## ets         19    ets            list     
## thetam      23    thetam         list     
## nnetar      15    nnetar         list     
## stlm         9    stlm           list     
## tbats       25    tbats          list     
## weights      6    -none-         numeric  
## frequency    1    -none-         numeric  
## x          324    ts             numeric  
## xreg         3    -none-         list     
## models       6    -none-         character
## fitted     324    -none-         numeric  
## residuals  324    ts             numeric</code></pre></div>
<p>Two types of plots can be created for the created ensemble model: either a plot showing the actual and fitted value of each component model on the data or individual plots of the component models as created by their regular S3 <code>plot()</code> methods. Note that a <code>plot()</code> method does not exist in the “forecast” package for objects generated with <code>stlm()</code>, so this component model will be ignored when <code>type = &quot;models&quot;</code>, but the other component models will be plotted regardless.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(hmod, <span class="dt">type =</span> <span class="st">&quot;fit&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:hmod3"></span>
<img src="bookdown-demo_files/figure-html/hmod3-1.png" alt="Actual and fitted value of each component model." width="672" />
<p class="caption">
Figure 12.3: Actual and fitted value of each component model.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(hmod, <span class="dt">type =</span> <span class="st">&quot;models&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:hmod4-1"></span>
<img src="bookdown-demo_files/figure-html/hmod4-1.png" alt="the actual and fitted value of each component model." width="672" />
<p class="caption">
Figure 12.4: the actual and fitted value of each component model.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:hmod4-2"></span>
<img src="bookdown-demo_files/figure-html/hmod4-2.png" alt="the actual and fitted value of each component model." width="672" />
<p class="caption">
Figure 12.5: the actual and fitted value of each component model.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:hmod4-3"></span>
<img src="bookdown-demo_files/figure-html/hmod4-3.png" alt="the actual and fitted value of each component model." width="672" />
<p class="caption">
Figure 12.6: the actual and fitted value of each component model.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:hmod4-4"></span>
<img src="bookdown-demo_files/figure-html/hmod4-4.png" alt="the actual and fitted value of each component model." width="672" />
<p class="caption">
Figure 12.7: the actual and fitted value of each component model.
</p>
</div>
</div>
<div id="forecasting" class="section level2">
<h2><span class="header-section-number">12.3</span> Forecasting</h2>
<p>Now's let's forecast future values. The <code>forecast()</code> function produce an S3 class forecast object for the next 14 days from the ensemble model. The prediction intervals are preserved from the individual component models and currently use the most extreme value from an individual model, producing a conservative estimate for the ensemble's performance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hfc &lt;-<span class="st"> </span><span class="kw">forecast</span>(hmod, <span class="dt">h =</span> <span class="dv">14</span>) 
<span class="co"># View the point forecasts</span>
hfc<span class="op">$</span>mean
## Time Series:
## Start = c(2042, 3) 
## End = c(2044, 2) 
## Frequency = 7 
##  [1] 106.59821  92.79875 104.66484 132.91459 128.86821
##  [6] 133.53789 145.27774 127.33009 109.45873 122.95030
## [11] 149.76991 143.77561 148.34727 157.04804
<span class="co"># View the upper prediction interval</span>
hfc<span class="op">$</span>upper
##            80%      95%
##  [1,] 154.8136 174.3183
##  [2,] 136.8427 156.7485
##  [3,] 149.4553 169.5050
##  [4,] 176.9789 194.6245
##  [5,] 176.0517 192.1269
##  [6,] 181.4409 203.3384
##  [7,] 213.5458 216.2529
##  [8,] 201.9121 204.1527
##  [9,] 180.0530 182.6926
## [10,] 218.6720 221.5546
## [11,] 235.7841 237.3367
## [12,] 225.0711 227.1369
## [13,] 231.8018 234.0672
## [14,] 248.0386 250.0807
<span class="co"># View the lower prediction interval</span>
hfc<span class="op">$</span>lower
##            80%        95%
##  [1,] 59.99658  39.379958
##  [2,] 25.58865   4.158083
##  [3,] 16.99737  -4.861073
##  [4,] 76.29264  55.328106
##  [5,] 66.55646  45.370109
##  [6,] 72.11097  50.721112
##  [7,] 76.98625  53.494111
##  [8,] 56.08554  32.202438
##  [9,] 21.00009  -3.267690
## [10,] 12.40980 -12.236645
## [11,] 72.15436  46.834814
## [12,] 62.19004  36.608705
## [13,] 67.52823  41.706667
## [14,] 73.45265  47.346402</code></pre></div>
<p>Now, we plot the forecast for the next 14 days with the prediction intervals.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Plot the forecast</span>
<span class="kw">plot</span>(hfc, <span class="dt">xlab =</span> <span class="st">&quot;Days&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Daily new deaths&quot;</span>, 
     <span class="dt">main =</span> <span class="st">&quot;Ensembled forecast from different methods&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:hmod5"></span>
<img src="bookdown-demo_files/figure-html/hmod5-1.png" alt="Two weeks ahead ensemble forecast from different methods." width="672" />
<p class="caption">
Figure 12.8: Two weeks ahead ensemble forecast from different methods.
</p>
</div>
<p>After the model is fit, these weights are stored in the weights attribute of the model. The user can view and manipulated these weights after the fit is complete. Note that the <code>hybridModel()</code> function automatically scales weights to sum to one, so a user should similar scale the weights to ensure the forecasts remain unbiased. Furthermore, the vector that replaces weights must retain names specifying the component model it corresponds to since weights are not assigned by position but rather by component name. Similarly, individual components may also be replaced.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hmod<span class="op">$</span>weights
## auto.arima        ets     thetam     nnetar       stlm 
##  0.1666667  0.1666667  0.1666667  0.1666667  0.1666667 
##      tbats 
##  0.1666667</code></pre></div>
<div id="perform-cross-validation-on-a-time-series" class="section level3">
<h3><span class="header-section-number">12.3.1</span> Perform cross validation on a time series</h3>
<p>It can be useful to perform cross validation on a forecasting model to estimate a model's out-of-sample forecasting performance. Cross validation of time series data is more complicated than regular k-folds or leave-one-out cross validation of datasets without serial correlation since observations <span class="math inline">\(x_t\)</span> and <span class="math inline">\(x_{t+n}\)</span> are not independent.</p>
<p>The <code>cvts()</code> function overcomes this obstacle using two methods: 1) rolling cross validation where an initial training window is used along with a forecast horizon and the initial window used for training grows by one observation each round until the training window and the forecast horizon capture the entire series; or 2) a non-rolling approach where a fixed training length is used that is shifted forward by the forecast horizon after each iteration.</p>
<p>For example, let's perform cross validation for a <code>stlm()</code> model and a <code>naive()</code> model on the woolyrnq time series. The most important <code>cvts()</code> arguments that commonly need adjusting are rolling (if <code>TRUE</code>, the model will always be fit on a fixed <code>windowSize</code> instead of growing by one new observation for each new model fit during cross validation), <code>windowSize</code> (starting length of time series to fit a model), and <code>maxHorizon</code> (the forecast horizon for predictions from each model). Since a naive forecast is a good baseline that any decent model should surpass, let's see how the <code>stlm()</code> model compares.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stlmMod &lt;-<span class="st"> </span><span class="kw">cvts</span>(y, <span class="dt">FUN =</span> stlm, <span class="dt">windowSize =</span> <span class="dv">100</span>, <span class="dt">maxHorizon =</span> <span class="dv">7</span>)
naiveMod &lt;-<span class="st"> </span><span class="kw">cvts</span>(y, <span class="dt">FUN =</span> naive, <span class="dt">windowSize =</span> <span class="dv">100</span>, <span class="dt">maxHorizon =</span> <span class="dv">7</span>)
<span class="kw">accuracy</span>(stlmMod)
##                             ME     RMSE      MAE
## Forecast Horizon  1 -0.9068629 31.27580 23.69878
## Forecast Horizon  2 -2.6490705 43.91947 27.06993
## Forecast Horizon  3 -1.2864292 37.85213 28.29804
## Forecast Horizon  4 -2.2917024 36.27865 27.61824
## Forecast Horizon  5 -2.9254922 30.23136 22.62086
## Forecast Horizon  6 -6.4138820 51.77928 35.64043
## Forecast Horizon  7 -1.7238578 38.63659 29.09958
<span class="kw">accuracy</span>(naiveMod)
##                            ME     RMSE      MAE
## Forecast Horizon  1 -20.78125 39.26791 28.46875
## Forecast Horizon  2 -58.06250 74.62448 61.87500
## Forecast Horizon  3 -52.71875 68.61054 54.09375
## Forecast Horizon  4   5.06250 35.96526 27.18750
## Forecast Horizon  5   6.09375 34.76394 27.09375
## Forecast Horizon  6   6.37500 52.37246 37.00000
## Forecast Horizon  7   2.37500 39.79871 27.31250</code></pre></div>
</div>
</div>
<div id="weights-selection-using-cross-validation" class="section level2">
<h2><span class="header-section-number">12.4</span> Weights Selection Using Cross Validation</h2>
<p>Previously we explored fitting <code>hybridModel()</code> objects with <code>weights = &quot;equal&quot;</code> or <code>weights = &quot;insample.errors&quot;</code>, but we can now leverage the process conducted in <code>cvts()</code> to select the appropriate weights intelligently based on the expected out-of-sample forecast accuracy of each component model. While this is the methodologically-sound weight procedure, it also comes at significant computational cost since the cross validation procedure necessitates fitting each model several times for each cross validation fold in addition to the final fit on the whole dataset. Fortunately this process can be conducted in parallel if multiple cores are available. Some of the arguments explained above in <code>cvts()</code> such as <code>windowSize</code> and the <code>cvHorizon</code> can also be controlled here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cvMod &lt;-<span class="st"> </span><span class="kw">hybridModel</span>(y, <span class="dt">weights =</span> <span class="st">&quot;cv.errors&quot;</span>, <span class="dt">windowSize =</span> <span class="dv">100</span>,
                     <span class="dt">cvHorizon =</span> <span class="dv">8</span>, <span class="dt">num.cores =</span> <span class="dv">4</span>)
cvMod</code></pre></div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-assimakopoulos2000theta">
<p>Assimakopoulos, Vassilis, and Konstantinos Nikolopoulos. 2000. “The Theta Model: A Decomposition Approach to Forecasting.” <em>International Journal of Forecasting</em> 16 (4). Elsevier: 521–30.</p>
</div>
<div id="ref-bates1969combination">
<p>Bates, John M, and Clive WJ Granger. 1969. “The Combination of Forecasts.” <em>Journal of the Operational Research Society</em> 20 (4). Taylor &amp; Francis: 451–68.</p>
</div>
<div id="ref-de2011forecasting">
<p>De Livera, Alysha M, Rob J Hyndman, and Ralph D Snyder. 2011. “Forecasting Time Series with Complex Seasonal Patterns Using Exponential Smoothing.” <em>Journal of the American Statistical Association</em> 106 (496). Taylor &amp; Francis: 1513–27.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="NN.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/11-ensemble.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
